//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.24 at 05:49:08 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:samplr/entity/1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package samplr.sbapi.model.xsd;
